-- Phase 11: consent tracking (§5.5) and public REST v1 idempotency (§11.2). ApiKey,
-- OutboundWebhookSubscription/Delivery and DataSubjectRequest already exist from the Phase 2
-- schema; this migration adds the two models Phase 11 introduces new.

-- CreateEnum
CREATE TYPE "ConsentStatus" AS ENUM ('UNKNOWN', 'GRANTED', 'WITHDRAWN');

-- CreateTable
CREATE TABLE "ConsentRecord" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "identityId" TEXT NOT NULL,
    "channel" TEXT NOT NULL,
    "status" "ConsentStatus" NOT NULL DEFAULT 'UNKNOWN',
    "source" TEXT,
    "capturedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ConsentRecord_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ApiIdempotencyKey" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "apiKeyId" TEXT,
    "key" TEXT NOT NULL,
    "requestHash" TEXT NOT NULL,
    "responseStatus" INTEGER NOT NULL,
    "responseBody" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ApiIdempotencyKey_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ConsentRecord_workspaceId_identityId_channel_key" ON "ConsentRecord"("workspaceId", "identityId", "channel");
CREATE INDEX "ConsentRecord_workspaceId_identityId_idx" ON "ConsentRecord"("workspaceId", "identityId");
CREATE INDEX "ConsentRecord_workspaceId_channel_status_idx" ON "ConsentRecord"("workspaceId", "channel", "status");

CREATE UNIQUE INDEX "ApiIdempotencyKey_workspaceId_key_key" ON "ApiIdempotencyKey"("workspaceId", "key");
CREATE INDEX "ApiIdempotencyKey_workspaceId_createdAt_idx" ON "ApiIdempotencyKey"("workspaceId", "createdAt");
CREATE INDEX "ApiIdempotencyKey_apiKeyId_idx" ON "ApiIdempotencyKey"("apiKeyId");

-- AddForeignKey
ALTER TABLE "ConsentRecord" ADD CONSTRAINT "ConsentRecord_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ConsentRecord" ADD CONSTRAINT "ConsentRecord_identityId_fkey" FOREIGN KEY ("identityId") REFERENCES "Identity"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "ApiIdempotencyKey" ADD CONSTRAINT "ApiIdempotencyKey_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ApiIdempotencyKey" ADD CONSTRAINT "ApiIdempotencyKey_apiKeyId_fkey" FOREIGN KEY ("apiKeyId") REFERENCES "ApiKey"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- nexus:managed-outside-schema
-- Row-level security for the two new tenant tables (generated by scripts/gen-rls-sql.ts
-- --tables ConsentRecord,ApiIdempotencyKey — same policy shape as every other tenant table).
ALTER TABLE "ApiIdempotencyKey" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApiIdempotencyKey" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ApiIdempotencyKey_tenant ON "ApiIdempotencyKey";
CREATE POLICY rls_ApiIdempotencyKey_tenant ON "ApiIdempotencyKey"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "ConsentRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ConsentRecord" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ConsentRecord_tenant ON "ConsentRecord";
CREATE POLICY rls_ConsentRecord_tenant ON "ConsentRecord"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

-- Application role privileges (only when the role exists in this cluster).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nexus_app') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON "ConsentRecord" TO nexus_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON "ApiIdempotencyKey" TO nexus_app';
  END IF;
END $$;
