// GENERATED FILE — DO NOT EDIT.
// Produced by scripts/gen-tenant-models.ts from the Prisma runtime data model
// (every model that has a `workspaceId` field, plus relation metadata for the
// scoped client's nested traversal). Regenerate with:
//   pnpm --filter @nexus/db generate
// src/tenant-models.test.ts fails if this file is stale.

export const TENANT_MODELS: ReadonlySet<string> = new Set([
  'AiInsight',
  'ApiKey',
  'Attribute',
  'AttributePermission',
  'AuditLog',
  'Connection',
  'ConnectionDriftSample',
  'ConnectionGrant',
  'Conversation',
  'DataSubjectRequest',
  'DeadLetter',
  'Embedding',
  'ExternalObject',
  'FieldMapping',
  'FieldMappingRule',
  'Identity',
  'IdentityLink',
  'ImportJob',
  'IntegrationError',
  'Invitation',
  'List',
  'ListAttribute',
  'ListEntry',
  'ListStageHistory',
  'Membership',
  'MergeSuggestion',
  'Message',
  'NeverMerge',
  'Note',
  'ObjectType',
  'OutboundAction',
  'OutboundWebhookDelivery',
  'OutboundWebhookSubscription',
  'RateBudget',
  'Record',
  'RecordMerge',
  'RecordRelation',
  'SavedView',
  'SyncCursor',
  'SyncRun',
  'Task',
  'Team',
  'TeamMember',
  'TimelineEvent',
  'VaultEntry',
  'WebhookEvent',
  'Workflow',
  'WorkflowRun',
  'WorkspaceKey',
]);

export type RelationMeta = { model: string; isList: boolean };
export type ModelMeta = { table: string; relations: Record<string, RelationMeta> };

export const MODEL_META: Readonly<Record<string, ModelMeta>> = {
  Account: { table: 'Account', relations: { user: { model: 'User', isList: false } } },
  AiInsight: { table: 'AiInsight', relations: { workspace: { model: 'Workspace', isList: false }, record: { model: 'Record', isList: false }, conversation: { model: 'Conversation', isList: false }, acceptedBy: { model: 'User', isList: false } } },
  ApiKey: { table: 'ApiKey', relations: { workspace: { model: 'Workspace', isList: false }, createdBy: { model: 'User', isList: false } } },
  Attribute: { table: 'Attribute', relations: { workspace: { model: 'Workspace', isList: false }, objectType: { model: 'ObjectType', isList: false }, permissions: { model: 'AttributePermission', isList: true }, recordRelations: { model: 'RecordRelation', isList: true }, fieldMappingRules: { model: 'FieldMappingRule', isList: true } } },
  AttributePermission: { table: 'AttributePermission', relations: { workspace: { model: 'Workspace', isList: false }, attribute: { model: 'Attribute', isList: false } } },
  AuditLog: { table: 'AuditLog', relations: { workspace: { model: 'Workspace', isList: false }, actorUser: { model: 'User', isList: false } } },
  Connection: { table: 'Connection', relations: { workspace: { model: 'Workspace', isList: false }, fieldMapping: { model: 'FieldMapping', isList: false }, owner: { model: 'User', isList: false }, grants: { model: 'ConnectionGrant', isList: true }, driftSamples: { model: 'ConnectionDriftSample', isList: true }, syncCursors: { model: 'SyncCursor', isList: true }, syncRuns: { model: 'SyncRun', isList: true }, externalObjects: { model: 'ExternalObject', isList: true }, webhookEvents: { model: 'WebhookEvent', isList: true }, rateBudgets: { model: 'RateBudget', isList: true }, outboundActions: { model: 'OutboundAction', isList: true }, integrationErrors: { model: 'IntegrationError', isList: true }, conversations: { model: 'Conversation', isList: true }, timelineEvents: { model: 'TimelineEvent', isList: true }, deadLetters: { model: 'DeadLetter', isList: true } } },
  ConnectionDriftSample: { table: 'ConnectionDriftSample', relations: { workspace: { model: 'Workspace', isList: false }, connection: { model: 'Connection', isList: false } } },
  ConnectionGrant: { table: 'ConnectionGrant', relations: { workspace: { model: 'Workspace', isList: false }, connection: { model: 'Connection', isList: false } } },
  Conversation: { table: 'Conversation', relations: { workspace: { model: 'Workspace', isList: false }, connection: { model: 'Connection', isList: false }, identity: { model: 'Identity', isList: false }, personRecord: { model: 'Record', isList: false }, assignee: { model: 'User', isList: false }, messages: { model: 'Message', isList: true }, outboundActions: { model: 'OutboundAction', isList: true }, aiInsights: { model: 'AiInsight', isList: true }, tasks: { model: 'Task', isList: true }, notes: { model: 'Note', isList: true } } },
  DataSubjectRequest: { table: 'DataSubjectRequest', relations: { workspace: { model: 'Workspace', isList: false }, subjectRecord: { model: 'Record', isList: false }, requestedBy: { model: 'User', isList: false } } },
  DeadLetter: { table: 'DeadLetter', relations: { workspace: { model: 'Workspace', isList: false }, connection: { model: 'Connection', isList: false } } },
  Embedding: { table: 'Embedding', relations: { workspace: { model: 'Workspace', isList: false } } },
  ExternalObject: { table: 'ExternalObject', relations: { workspace: { model: 'Workspace', isList: false }, connection: { model: 'Connection', isList: false }, timelineEvents: { model: 'TimelineEvent', isList: true }, integrationErrors: { model: 'IntegrationError', isList: true } } },
  FieldMapping: { table: 'FieldMapping', relations: { workspace: { model: 'Workspace', isList: false }, rules: { model: 'FieldMappingRule', isList: true }, connections: { model: 'Connection', isList: true } } },
  FieldMappingRule: { table: 'FieldMappingRule', relations: { workspace: { model: 'Workspace', isList: false }, fieldMapping: { model: 'FieldMapping', isList: false }, attribute: { model: 'Attribute', isList: false } } },
  Identity: { table: 'Identity', relations: { workspace: { model: 'Workspace', isList: false }, personRecord: { model: 'Record', isList: false }, links: { model: 'IdentityLink', isList: true }, mergeSuggestions: { model: 'MergeSuggestion', isList: true }, conversations: { model: 'Conversation', isList: true }, authoredMessages: { model: 'Message', isList: true }, timelineEvents: { model: 'TimelineEvent', isList: true }, timelineEventsActed: { model: 'TimelineEvent', isList: true } } },
  IdentityLink: { table: 'IdentityLink', relations: { workspace: { model: 'Workspace', isList: false }, identity: { model: 'Identity', isList: false }, personRecord: { model: 'Record', isList: false }, confirmedBy: { model: 'User', isList: false } } },
  ImportJob: { table: 'ImportJob', relations: { workspace: { model: 'Workspace', isList: false }, objectType: { model: 'ObjectType', isList: false }, createdBy: { model: 'User', isList: false }, records: { model: 'Record', isList: true } } },
  IntegrationError: { table: 'IntegrationError', relations: { workspace: { model: 'Workspace', isList: false }, connection: { model: 'Connection', isList: false }, syncRun: { model: 'SyncRun', isList: false }, externalObject: { model: 'ExternalObject', isList: false }, outboundAction: { model: 'OutboundAction', isList: false }, resolvedBy: { model: 'User', isList: false } } },
  Invitation: { table: 'Invitation', relations: { workspace: { model: 'Workspace', isList: false }, invitedBy: { model: 'User', isList: false } } },
  List: { table: 'List', relations: { workspace: { model: 'Workspace', isList: false }, objectType: { model: 'ObjectType', isList: false }, attributes: { model: 'ListAttribute', isList: true }, entries: { model: 'ListEntry', isList: true }, savedViews: { model: 'SavedView', isList: true } } },
  ListAttribute: { table: 'ListAttribute', relations: { workspace: { model: 'Workspace', isList: false }, list: { model: 'List', isList: false } } },
  ListEntry: { table: 'ListEntry', relations: { workspace: { model: 'Workspace', isList: false }, list: { model: 'List', isList: false }, record: { model: 'Record', isList: false }, stageHistory: { model: 'ListStageHistory', isList: true } } },
  ListStageHistory: { table: 'ListStageHistory', relations: { workspace: { model: 'Workspace', isList: false }, listEntry: { model: 'ListEntry', isList: false }, changedBy: { model: 'User', isList: false } } },
  Membership: { table: 'Membership', relations: { workspace: { model: 'Workspace', isList: false }, user: { model: 'User', isList: false }, invitedBy: { model: 'User', isList: false } } },
  MergeSuggestion: { table: 'MergeSuggestion', relations: { workspace: { model: 'Workspace', isList: false }, leftRecord: { model: 'Record', isList: false }, identity: { model: 'Identity', isList: false }, rightRecord: { model: 'Record', isList: false }, decidedBy: { model: 'User', isList: false } } },
  Message: { table: 'Message', relations: { workspace: { model: 'Workspace', isList: false }, conversation: { model: 'Conversation', isList: false }, authorIdentity: { model: 'Identity', isList: false }, authorUser: { model: 'User', isList: false }, outboundAction: { model: 'OutboundAction', isList: false } } },
  NeverMerge: { table: 'NeverMerge', relations: { workspace: { model: 'Workspace', isList: false }, leftRecord: { model: 'Record', isList: false }, rightRecord: { model: 'Record', isList: false }, decidedBy: { model: 'User', isList: false } } },
  Note: { table: 'Note', relations: { workspace: { model: 'Workspace', isList: false }, record: { model: 'Record', isList: false }, conversation: { model: 'Conversation', isList: false }, author: { model: 'User', isList: false } } },
  ObjectType: { table: 'ObjectType', relations: { workspace: { model: 'Workspace', isList: false }, attributes: { model: 'Attribute', isList: true }, records: { model: 'Record', isList: true }, lists: { model: 'List', isList: true }, savedViews: { model: 'SavedView', isList: true }, importJobs: { model: 'ImportJob', isList: true } } },
  OutboundAction: { table: 'OutboundAction', relations: { workspace: { model: 'Workspace', isList: false }, connection: { model: 'Connection', isList: false }, conversation: { model: 'Conversation', isList: false }, requestedBy: { model: 'User', isList: false }, approvedBy: { model: 'User', isList: false }, messages: { model: 'Message', isList: true }, errors: { model: 'IntegrationError', isList: true } } },
  OutboundWebhookDelivery: { table: 'OutboundWebhookDelivery', relations: { workspace: { model: 'Workspace', isList: false }, subscription: { model: 'OutboundWebhookSubscription', isList: false } } },
  OutboundWebhookSubscription: { table: 'OutboundWebhookSubscription', relations: { workspace: { model: 'Workspace', isList: false }, createdBy: { model: 'User', isList: false }, deliveries: { model: 'OutboundWebhookDelivery', isList: true } } },
  PlatformComplianceNote: { table: 'PlatformComplianceNote', relations: {  } },
  RateBudget: { table: 'RateBudget', relations: { workspace: { model: 'Workspace', isList: false }, connection: { model: 'Connection', isList: false } } },
  Record: { table: 'Record', relations: { workspace: { model: 'Workspace', isList: false }, objectType: { model: 'ObjectType', isList: false }, createdBy: { model: 'User', isList: false }, importJob: { model: 'ImportJob', isList: false }, mergedInto: { model: 'Record', isList: false }, mergedFrom: { model: 'Record', isList: true }, relationsFrom: { model: 'RecordRelation', isList: true }, relationsTo: { model: 'RecordRelation', isList: true }, listEntries: { model: 'ListEntry', isList: true }, identities: { model: 'Identity', isList: true }, identityLinks: { model: 'IdentityLink', isList: true }, mergeSuggestionsLeft: { model: 'MergeSuggestion', isList: true }, mergeSuggestionsRight: { model: 'MergeSuggestion', isList: true }, neverMergeLeft: { model: 'NeverMerge', isList: true }, neverMergeRight: { model: 'NeverMerge', isList: true }, mergesWon: { model: 'RecordMerge', isList: true }, mergesLost: { model: 'RecordMerge', isList: true }, conversations: { model: 'Conversation', isList: true }, timelineEvents: { model: 'TimelineEvent', isList: true }, aiInsights: { model: 'AiInsight', isList: true }, tasks: { model: 'Task', isList: true }, notes: { model: 'Note', isList: true }, dataSubjectRequests: { model: 'DataSubjectRequest', isList: true } } },
  RecordMerge: { table: 'RecordMerge', relations: { workspace: { model: 'Workspace', isList: false }, winner: { model: 'Record', isList: false }, loser: { model: 'Record', isList: false }, mergedBy: { model: 'User', isList: false }, unmergedBy: { model: 'User', isList: false } } },
  RecordRelation: { table: 'RecordRelation', relations: { workspace: { model: 'Workspace', isList: false }, fromRecord: { model: 'Record', isList: false }, toRecord: { model: 'Record', isList: false }, attribute: { model: 'Attribute', isList: false } } },
  SavedView: { table: 'SavedView', relations: { workspace: { model: 'Workspace', isList: false }, objectType: { model: 'ObjectType', isList: false }, list: { model: 'List', isList: false }, owner: { model: 'User', isList: false } } },
  Session: { table: 'Session', relations: { user: { model: 'User', isList: false } } },
  SyncCursor: { table: 'SyncCursor', relations: { workspace: { model: 'Workspace', isList: false }, connection: { model: 'Connection', isList: false } } },
  SyncRun: { table: 'SyncRun', relations: { workspace: { model: 'Workspace', isList: false }, connection: { model: 'Connection', isList: false }, errors: { model: 'IntegrationError', isList: true } } },
  Task: { table: 'Task', relations: { workspace: { model: 'Workspace', isList: false }, assignee: { model: 'User', isList: false }, createdBy: { model: 'User', isList: false }, record: { model: 'Record', isList: false }, conversation: { model: 'Conversation', isList: false } } },
  Team: { table: 'Team', relations: { workspace: { model: 'Workspace', isList: false }, members: { model: 'TeamMember', isList: true } } },
  TeamMember: { table: 'TeamMember', relations: { workspace: { model: 'Workspace', isList: false }, team: { model: 'Team', isList: false }, user: { model: 'User', isList: false } } },
  TimelineEvent: { table: 'TimelineEvent', relations: { workspace: { model: 'Workspace', isList: false }, record: { model: 'Record', isList: false }, identity: { model: 'Identity', isList: false }, connection: { model: 'Connection', isList: false }, actorIdentity: { model: 'Identity', isList: false }, actorUser: { model: 'User', isList: false }, externalObject: { model: 'ExternalObject', isList: false } } },
  User: { table: 'User', relations: { accounts: { model: 'Account', isList: true }, sessions: { model: 'Session', isList: true }, memberships: { model: 'Membership', isList: true }, sentInvitations: { model: 'Invitation', isList: true }, importJobs: { model: 'ImportJob', isList: true }, invitedMemberships: { model: 'Membership', isList: true }, teamMemberships: { model: 'TeamMember', isList: true }, createdRecords: { model: 'Record', isList: true }, listStageChanges: { model: 'ListStageHistory', isList: true }, savedViews: { model: 'SavedView', isList: true }, confirmedIdentityLinks: { model: 'IdentityLink', isList: true }, decidedMergeSuggestions: { model: 'MergeSuggestion', isList: true }, neverMergeDecisions: { model: 'NeverMerge', isList: true }, mergesPerformed: { model: 'RecordMerge', isList: true }, unmergesPerformed: { model: 'RecordMerge', isList: true }, assignedConversations: { model: 'Conversation', isList: true }, authoredMessages: { model: 'Message', isList: true }, timelineEventsActed: { model: 'TimelineEvent', isList: true }, ownedConnections: { model: 'Connection', isList: true }, requestedOutboundActions: { model: 'OutboundAction', isList: true }, approvedOutboundActions: { model: 'OutboundAction', isList: true }, resolvedIntegrationErrors: { model: 'IntegrationError', isList: true }, createdWorkflows: { model: 'Workflow', isList: true }, acceptedAiInsights: { model: 'AiInsight', isList: true }, auditLogs: { model: 'AuditLog', isList: true }, assignedTasks: { model: 'Task', isList: true }, createdTasks: { model: 'Task', isList: true }, notes: { model: 'Note', isList: true }, apiKeys: { model: 'ApiKey', isList: true }, outboundWebhookSubscriptions: { model: 'OutboundWebhookSubscription', isList: true }, dataSubjectRequests: { model: 'DataSubjectRequest', isList: true } } },
  VaultEntry: { table: 'VaultEntry', relations: { workspace: { model: 'Workspace', isList: false }, key: { model: 'WorkspaceKey', isList: false } } },
  VerificationToken: { table: 'VerificationToken', relations: {  } },
  WebhookEvent: { table: 'WebhookEvent', relations: { workspace: { model: 'Workspace', isList: false }, connection: { model: 'Connection', isList: false } } },
  Workflow: { table: 'Workflow', relations: { workspace: { model: 'Workspace', isList: false }, createdBy: { model: 'User', isList: false }, runs: { model: 'WorkflowRun', isList: true } } },
  WorkflowRun: { table: 'WorkflowRun', relations: { workspace: { model: 'Workspace', isList: false }, workflow: { model: 'Workflow', isList: false } } },
  Workspace: { table: 'Workspace', relations: { memberships: { model: 'Membership', isList: true }, invitations: { model: 'Invitation', isList: true }, importJobs: { model: 'ImportJob', isList: true }, teams: { model: 'Team', isList: true }, teamMembers: { model: 'TeamMember', isList: true }, objectTypes: { model: 'ObjectType', isList: true }, attributes: { model: 'Attribute', isList: true }, attributePermissions: { model: 'AttributePermission', isList: true }, records: { model: 'Record', isList: true }, recordRelations: { model: 'RecordRelation', isList: true }, recordMerges: { model: 'RecordMerge', isList: true }, lists: { model: 'List', isList: true }, listAttributes: { model: 'ListAttribute', isList: true }, listEntries: { model: 'ListEntry', isList: true }, listStageHistory: { model: 'ListStageHistory', isList: true }, savedViews: { model: 'SavedView', isList: true }, identities: { model: 'Identity', isList: true }, identityLinks: { model: 'IdentityLink', isList: true }, mergeSuggestions: { model: 'MergeSuggestion', isList: true }, neverMerges: { model: 'NeverMerge', isList: true }, conversations: { model: 'Conversation', isList: true }, messages: { model: 'Message', isList: true }, timelineEvents: { model: 'TimelineEvent', isList: true }, connections: { model: 'Connection', isList: true }, connectionGrants: { model: 'ConnectionGrant', isList: true }, connectionDriftSamples: { model: 'ConnectionDriftSample', isList: true }, syncCursors: { model: 'SyncCursor', isList: true }, syncRuns: { model: 'SyncRun', isList: true }, externalObjects: { model: 'ExternalObject', isList: true }, webhookEvents: { model: 'WebhookEvent', isList: true }, rateBudgets: { model: 'RateBudget', isList: true }, outboundActions: { model: 'OutboundAction', isList: true }, integrationErrors: { model: 'IntegrationError', isList: true }, fieldMappings: { model: 'FieldMapping', isList: true }, fieldMappingRules: { model: 'FieldMappingRule', isList: true }, workflows: { model: 'Workflow', isList: true }, workflowRuns: { model: 'WorkflowRun', isList: true }, aiInsights: { model: 'AiInsight', isList: true }, embeddings: { model: 'Embedding', isList: true }, auditLogs: { model: 'AuditLog', isList: true }, tasks: { model: 'Task', isList: true }, notes: { model: 'Note', isList: true }, apiKeys: { model: 'ApiKey', isList: true }, outboundWebhookSubscriptions: { model: 'OutboundWebhookSubscription', isList: true }, outboundWebhookDeliveries: { model: 'OutboundWebhookDelivery', isList: true }, dataSubjectRequests: { model: 'DataSubjectRequest', isList: true }, workspaceKeys: { model: 'WorkspaceKey', isList: true }, vaultEntries: { model: 'VaultEntry', isList: true }, deadLetters: { model: 'DeadLetter', isList: true } } },
  WorkspaceKey: { table: 'WorkspaceKey', relations: { workspace: { model: 'Workspace', isList: false }, entries: { model: 'VaultEntry', isList: true } } },
};
