// GENERATED FILE — DO NOT EDIT.
// Produced by scripts/gen-tenant-models.ts from the Prisma runtime data model
// (every model that has a `workspaceId` field). Regenerate with:
//   pnpm --filter @nexus/db generate
// src/tenant-models.test.ts fails if this file is stale.

export const TENANT_MODELS: ReadonlySet<string> = new Set([
  'AiInsight',
  'ApiKey',
  'Attribute',
  'AttributePermission',
  'AuditLog',
  'Connection',
  'ConnectionDriftSample',
  'ConnectionGrant',
  'Conversation',
  'DataSubjectRequest',
  'Embedding',
  'ExternalObject',
  'FieldMapping',
  'FieldMappingRule',
  'Identity',
  'IdentityLink',
  'IntegrationError',
  'List',
  'ListAttribute',
  'ListEntry',
  'ListStageHistory',
  'Membership',
  'MergeSuggestion',
  'Message',
  'NeverMerge',
  'Note',
  'ObjectType',
  'OutboundAction',
  'OutboundWebhookDelivery',
  'OutboundWebhookSubscription',
  'RateBudget',
  'Record',
  'RecordMerge',
  'RecordRelation',
  'SavedView',
  'SyncCursor',
  'SyncRun',
  'Task',
  'Team',
  'TeamMember',
  'TimelineEvent',
  'WebhookEvent',
  'Workflow',
  'WorkflowRun',
]);
