-- nexus:managed-outside-schema
-- Row-level security (spec §5.1). Generated by scripts/gen-rls-sql.ts — do not hand-edit;
-- regenerate into a new migration when tenant models are added.
--
-- The application connects as the non-superuser role "nexus_app" (created by infra, see
-- infra/postgres/init.sql and the CI workflow). Migrations run as the table owner. FORCE makes
-- the policies apply to the owner too, so even a misconfigured DATABASE_URL is contained.

DROP FUNCTION IF EXISTS nexus_current_workspace();
CREATE FUNCTION nexus_current_workspace() RETURNS text
  LANGUAGE sql STABLE PARALLEL SAFE
  AS $$ SELECT NULLIF(current_setting('app.workspace_id', true), '') $$;

CREATE OR REPLACE FUNCTION nexus_rls_bypass() RETURNS boolean
  LANGUAGE sql STABLE PARALLEL SAFE
  AS $$ SELECT COALESCE(current_setting('app.rls_bypass', true), '') = 'on' $$;

-- The tenant root is reachable only as the current workspace (or with bypass).
ALTER TABLE "Workspace" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Workspace" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Workspace_tenant ON "Workspace";
CREATE POLICY rls_Workspace_tenant ON "Workspace"
  USING ("id" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("id" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "AiInsight" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiInsight" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_AiInsight_tenant ON "AiInsight";
CREATE POLICY rls_AiInsight_tenant ON "AiInsight"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "ApiKey" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApiKey" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ApiKey_tenant ON "ApiKey";
CREATE POLICY rls_ApiKey_tenant ON "ApiKey"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "Attribute" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Attribute" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Attribute_tenant ON "Attribute";
CREATE POLICY rls_Attribute_tenant ON "Attribute"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "AttributePermission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AttributePermission" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_AttributePermission_tenant ON "AttributePermission";
CREATE POLICY rls_AttributePermission_tenant ON "AttributePermission"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_AuditLog_tenant ON "AuditLog";
CREATE POLICY rls_AuditLog_tenant ON "AuditLog"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "Connection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Connection" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Connection_tenant ON "Connection";
CREATE POLICY rls_Connection_tenant ON "Connection"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "ConnectionDriftSample" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ConnectionDriftSample" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ConnectionDriftSample_tenant ON "ConnectionDriftSample";
CREATE POLICY rls_ConnectionDriftSample_tenant ON "ConnectionDriftSample"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "ConnectionGrant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ConnectionGrant" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ConnectionGrant_tenant ON "ConnectionGrant";
CREATE POLICY rls_ConnectionGrant_tenant ON "ConnectionGrant"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "Conversation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Conversation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Conversation_tenant ON "Conversation";
CREATE POLICY rls_Conversation_tenant ON "Conversation"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "DataSubjectRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DataSubjectRequest" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_DataSubjectRequest_tenant ON "DataSubjectRequest";
CREATE POLICY rls_DataSubjectRequest_tenant ON "DataSubjectRequest"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "Embedding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Embedding" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Embedding_tenant ON "Embedding";
CREATE POLICY rls_Embedding_tenant ON "Embedding"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "ExternalObject" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExternalObject" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ExternalObject_tenant ON "ExternalObject";
CREATE POLICY rls_ExternalObject_tenant ON "ExternalObject"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "FieldMapping" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FieldMapping" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_FieldMapping_tenant ON "FieldMapping";
CREATE POLICY rls_FieldMapping_tenant ON "FieldMapping"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "FieldMappingRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FieldMappingRule" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_FieldMappingRule_tenant ON "FieldMappingRule";
CREATE POLICY rls_FieldMappingRule_tenant ON "FieldMappingRule"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "Identity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Identity" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Identity_tenant ON "Identity";
CREATE POLICY rls_Identity_tenant ON "Identity"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "IdentityLink" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "IdentityLink" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_IdentityLink_tenant ON "IdentityLink";
CREATE POLICY rls_IdentityLink_tenant ON "IdentityLink"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "IntegrationError" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "IntegrationError" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_IntegrationError_tenant ON "IntegrationError";
CREATE POLICY rls_IntegrationError_tenant ON "IntegrationError"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "Invitation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invitation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Invitation_tenant ON "Invitation";
CREATE POLICY rls_Invitation_tenant ON "Invitation"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "List" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "List" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_List_tenant ON "List";
CREATE POLICY rls_List_tenant ON "List"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "ListAttribute" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ListAttribute" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ListAttribute_tenant ON "ListAttribute";
CREATE POLICY rls_ListAttribute_tenant ON "ListAttribute"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "ListEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ListEntry" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ListEntry_tenant ON "ListEntry";
CREATE POLICY rls_ListEntry_tenant ON "ListEntry"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "ListStageHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ListStageHistory" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ListStageHistory_tenant ON "ListStageHistory";
CREATE POLICY rls_ListStageHistory_tenant ON "ListStageHistory"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "Membership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Membership" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Membership_tenant ON "Membership";
CREATE POLICY rls_Membership_tenant ON "Membership"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "MergeSuggestion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MergeSuggestion" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_MergeSuggestion_tenant ON "MergeSuggestion";
CREATE POLICY rls_MergeSuggestion_tenant ON "MergeSuggestion"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "Message" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Message" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Message_tenant ON "Message";
CREATE POLICY rls_Message_tenant ON "Message"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "NeverMerge" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NeverMerge" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_NeverMerge_tenant ON "NeverMerge";
CREATE POLICY rls_NeverMerge_tenant ON "NeverMerge"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "Note" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Note" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Note_tenant ON "Note";
CREATE POLICY rls_Note_tenant ON "Note"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "ObjectType" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ObjectType" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ObjectType_tenant ON "ObjectType";
CREATE POLICY rls_ObjectType_tenant ON "ObjectType"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "OutboundAction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OutboundAction" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_OutboundAction_tenant ON "OutboundAction";
CREATE POLICY rls_OutboundAction_tenant ON "OutboundAction"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "OutboundWebhookDelivery" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OutboundWebhookDelivery" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_OutboundWebhookDelivery_tenant ON "OutboundWebhookDelivery";
CREATE POLICY rls_OutboundWebhookDelivery_tenant ON "OutboundWebhookDelivery"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "OutboundWebhookSubscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OutboundWebhookSubscription" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_OutboundWebhookSubscription_tenant ON "OutboundWebhookSubscription";
CREATE POLICY rls_OutboundWebhookSubscription_tenant ON "OutboundWebhookSubscription"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "RateBudget" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RateBudget" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_RateBudget_tenant ON "RateBudget";
CREATE POLICY rls_RateBudget_tenant ON "RateBudget"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "Record" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Record" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Record_tenant ON "Record";
CREATE POLICY rls_Record_tenant ON "Record"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "RecordMerge" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecordMerge" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_RecordMerge_tenant ON "RecordMerge";
CREATE POLICY rls_RecordMerge_tenant ON "RecordMerge"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "RecordRelation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecordRelation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_RecordRelation_tenant ON "RecordRelation";
CREATE POLICY rls_RecordRelation_tenant ON "RecordRelation"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "SavedView" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SavedView" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_SavedView_tenant ON "SavedView";
CREATE POLICY rls_SavedView_tenant ON "SavedView"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "SyncCursor" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SyncCursor" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_SyncCursor_tenant ON "SyncCursor";
CREATE POLICY rls_SyncCursor_tenant ON "SyncCursor"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "SyncRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SyncRun" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_SyncRun_tenant ON "SyncRun";
CREATE POLICY rls_SyncRun_tenant ON "SyncRun"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "Task" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Task" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Task_tenant ON "Task";
CREATE POLICY rls_Task_tenant ON "Task"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "Team" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Team" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Team_tenant ON "Team";
CREATE POLICY rls_Team_tenant ON "Team"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "TeamMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeamMember" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_TeamMember_tenant ON "TeamMember";
CREATE POLICY rls_TeamMember_tenant ON "TeamMember"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "TimelineEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TimelineEvent" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_TimelineEvent_tenant ON "TimelineEvent";
CREATE POLICY rls_TimelineEvent_tenant ON "TimelineEvent"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "WebhookEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WebhookEvent" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_WebhookEvent_tenant ON "WebhookEvent";
CREATE POLICY rls_WebhookEvent_tenant ON "WebhookEvent"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "Workflow" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Workflow" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Workflow_tenant ON "Workflow";
CREATE POLICY rls_Workflow_tenant ON "Workflow"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "WorkflowRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkflowRun" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_WorkflowRun_tenant ON "WorkflowRun";
CREATE POLICY rls_WorkflowRun_tenant ON "WorkflowRun"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

-- Application role privileges (only when the role exists in this cluster).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nexus_app') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA public TO nexus_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO nexus_app';
    EXECUTE 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nexus_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nexus_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO nexus_app';
  END IF;
END $$;
