/**
 * @nexus/connector-sdk — the connector SPI, canonical entity schemas, manifest
 * and quota shapes (spec §7), plus the Phase 4 runtime: OAuth helpers, envelope
 * encryption, the four-shape rate limiter, circuit breaker, HTTP client, webhook
 * verification and the quota simulator. The contract test suite is exported from
 * `@nexus/connector-sdk/contract` and test doubles from `@nexus/connector-sdk/testing`.
 */

export { PLATFORMS, platformSchema, type Platform } from './platform.ts';

export {
  CAPABILITIES,
  capabilitySchema,
  type Capability,
  type ReadCapability,
  type WriteCapability,
} from './capability.ts';

export {
  LANES,
  LANE_PRIORITY,
  laneSchema,
  endpointIdSchema,
  fixedWindowQuotaSchema,
  rollingHourQuotaSchema,
  dailyUnitsQuotaSchema,
  meteredCreditsQuotaSchema,
  quotaModelSchema,
  QUOTA_KINDS,
  type Lane,
  type FixedWindowQuota,
  type RollingHourQuota,
  type DailyUnitsQuota,
  type MeteredCreditsQuota,
  type QuotaModel,
  type QuotaKind,
  type BudgetSource,
  type BudgetWindow,
  type CircuitState,
  type BudgetSnapshot,
} from './quota.ts';

export {
  resourceIdSchema,
  resourceDescriptorSchema,
  authKindSchema,
  webhookVerificationSchema,
  scopeDescriptorSchema,
  connectorManifestSchema,
  type ResourceDescriptor,
  type AuthKind,
  type WebhookVerification,
  type ScopeDescriptor,
  type ConnectorManifest,
} from './manifest.ts';

export {
  e164Schema,
  timezoneSchema,
  currencyCodeSchema,
  attachmentSchema,
  canonicalBaseSchema,
  threadingSchema,
  canonicalPersonSchema,
  canonicalCompanySchema,
  conversationTypeSchema,
  participantSchema,
  canonicalConversationSchema,
  messageTypeSchema,
  canonicalMessageSchema,
  canonicalPostSchema,
  engagementTypeSchema,
  canonicalEngagementSchema,
  leadFieldSchema,
  canonicalLeadSchema,
  canonicalReviewSchema,
  metricGranularitySchema,
  canonicalMetricSchema,
  KEITARO_STANDARD_STATUSES,
  conversionStatusSchema,
  SUB_ID_KEYS,
  subIdsSchema,
  canonicalConversionSchema,
  canonicalEntitySchema,
  CANONICAL_KINDS,
  type Attachment,
  type CanonicalBase,
  type CanonicalPerson,
  type CanonicalCompany,
  type ConversationType,
  type Participant,
  type CanonicalConversation,
  type MessageType,
  type CanonicalMessage,
  type CanonicalPost,
  type EngagementType,
  type CanonicalEngagement,
  type LeadField,
  type CanonicalLead,
  type CanonicalReview,
  type MetricGranularity,
  type CanonicalMetric,
  type StandardConversionStatus,
  type ConversionStatus,
  type SubIdKey,
  type SubIds,
  type CanonicalConversion,
  type CanonicalEntity,
  type CanonicalKind,
  type CanonicalEntityOf,
} from './canonical.ts';

export {
  resourceSettingSchema,
  businessHoursSchema,
  subIdMeaningSchema,
  connectionSettingsSchema,
  type ConnectionSettings,
  type ConnectionSettingsInput,
} from './settings.ts';

export {
  tokenSetSchema,
  discoveredAccountSchema,
  resourceRefSchema,
  rawItemSchema,
  rawPageSchema,
  webhookEnvelopeSchema,
  outboundActionKindSchema,
  outboundActionInputSchema,
  outboundResultSchema,
  type Result,
  type FailureClass,
  type AppCredentials,
  type PkcePair,
  type TokenSet,
  type AuthCtx,
  type Logger,
  type HttpRequest,
  type HttpResponse,
  type HttpClient,
  type ObservedUsage,
  type BudgetReservation,
  type ReserveRequest,
  type SettleOutcome,
  type BudgetHandle,
  type ConnCtx,
  type NormalizeCtx,
  type DiscoveredAccount,
  type ScopeVerification,
  type ResourceRef,
  type RawItem,
  type RawPage,
  type WebhookRequest,
  type WebhookEnvelope,
  type OutboundActionKind,
  type OutboundActionInput,
  type OutboundAction,
  type OutboundResult,
  type Preflight,
  type HealthStatus,
  type HealthCheck,
  type HealthReport,
  type Connector,
} from './spi.ts';

// ── Phase 4 runtime ─────────────────────────────────────────────────────────
export {
  encryptedBlobSchema,
  generateDataKey,
  encryptWithDataKey,
  decryptWithDataKey,
  decryptToString,
  localKeyProvider,
  generateMasterKeyBase64,
  type EncryptedBlob,
  type KeyProvider,
} from './runtime/envelope.ts';
export {
  generatePkcePair,
  oauthStatePayloadSchema,
  mintOauthState,
  verifyOauthState,
  buildAuthorizationUrl,
  parseTokenResponse,
  classifyOauthError,
  exchangeAuthorizationCode,
  refreshAccessToken,
  revokeToken,
  tokenLifecycle,
  REFRESH_AT_FRACTION,
  RECONNECT_WARNING_MS,
  type OauthStatePayload,
  type TokenLifecycle,
} from './runtime/oauth.ts';
export {
  MAX_ATTEMPTS,
  backoffDelayMs,
  nextDelayMs,
  isRetryable,
  shouldRetry,
  sleep,
  isAbortError,
  type BackoffOptions,
} from './runtime/retry.ts';
export { MemoryBudgetStore, type BudgetStore } from './runtime/budget-store.ts';
export { RedisBudgetStore, type RedisLike } from './runtime/redis-budget-store.ts';
export {
  CircuitBreaker,
  breakerKey,
  type BreakerDoc,
  type BreakerOptions,
  type CircuitDecision,
} from './runtime/circuit-breaker.ts';
export {
  RateLimiter,
  LANE_FRACTIONS,
  dayKeyIn,
  nextMidnightIn,
  type SpendCap,
  type LimiterOptions,
  type HandleParams,
} from './runtime/rate-limiter.ts';
export {
  createHttpClient,
  endpointOf,
  parseRetryAfter,
  observedFromHeaders,
  type FetchLike,
  type HttpClientOptions,
} from './runtime/http-client.ts';
export {
  verifyHmacSha256,
  signHmacSha256,
  verifySharedSecret,
  verifyJwtRs256,
  type Jwk,
  type JwtClaims,
} from './runtime/webhooks.ts';
export {
  simulateQuota,
  dailyCapacityOf,
  type SimulationInput,
  type SimulationResult,
  type ResourceEstimate,
} from './runtime/quota-simulator.ts';
