/**
 * @nexus/connector-sdk — the connector SPI, canonical entity schemas, manifest
 * and quota shapes (spec §7). Types, Zod schemas and constants only; the
 * runtime pieces (RateLimiter, OAuth helpers, TokenVault, contract test
 * suite) are Phase 4 and live beside this package.
 */

export { PLATFORMS, platformSchema, type Platform } from './platform.ts';

export {
  CAPABILITIES,
  capabilitySchema,
  type Capability,
  type ReadCapability,
  type WriteCapability,
} from './capability.ts';

export {
  LANES,
  LANE_PRIORITY,
  laneSchema,
  endpointIdSchema,
  fixedWindowQuotaSchema,
  rollingHourQuotaSchema,
  dailyUnitsQuotaSchema,
  meteredCreditsQuotaSchema,
  quotaModelSchema,
  QUOTA_KINDS,
  type Lane,
  type FixedWindowQuota,
  type RollingHourQuota,
  type DailyUnitsQuota,
  type MeteredCreditsQuota,
  type QuotaModel,
  type QuotaKind,
  type BudgetSource,
  type BudgetWindow,
  type CircuitState,
  type BudgetSnapshot,
} from './quota.ts';

export {
  resourceIdSchema,
  resourceDescriptorSchema,
  authKindSchema,
  webhookVerificationSchema,
  scopeDescriptorSchema,
  connectorManifestSchema,
  type ResourceDescriptor,
  type AuthKind,
  type WebhookVerification,
  type ScopeDescriptor,
  type ConnectorManifest,
} from './manifest.ts';

export {
  e164Schema,
  timezoneSchema,
  currencyCodeSchema,
  attachmentSchema,
  canonicalBaseSchema,
  threadingSchema,
  canonicalPersonSchema,
  canonicalCompanySchema,
  conversationTypeSchema,
  participantSchema,
  canonicalConversationSchema,
  messageTypeSchema,
  canonicalMessageSchema,
  canonicalPostSchema,
  engagementTypeSchema,
  canonicalEngagementSchema,
  leadFieldSchema,
  canonicalLeadSchema,
  canonicalReviewSchema,
  metricGranularitySchema,
  canonicalMetricSchema,
  KEITARO_STANDARD_STATUSES,
  conversionStatusSchema,
  SUB_ID_KEYS,
  subIdsSchema,
  canonicalConversionSchema,
  canonicalEntitySchema,
  CANONICAL_KINDS,
  type Attachment,
  type CanonicalBase,
  type CanonicalPerson,
  type CanonicalCompany,
  type ConversationType,
  type Participant,
  type CanonicalConversation,
  type MessageType,
  type CanonicalMessage,
  type CanonicalPost,
  type EngagementType,
  type CanonicalEngagement,
  type LeadField,
  type CanonicalLead,
  type CanonicalReview,
  type MetricGranularity,
  type CanonicalMetric,
  type StandardConversionStatus,
  type ConversionStatus,
  type SubIdKey,
  type SubIds,
  type CanonicalConversion,
  type CanonicalEntity,
  type CanonicalKind,
  type CanonicalEntityOf,
} from './canonical.ts';

export {
  resourceSettingSchema,
  businessHoursSchema,
  subIdMeaningSchema,
  connectionSettingsSchema,
  type ConnectionSettings,
  type ConnectionSettingsInput,
} from './settings.ts';

export {
  tokenSetSchema,
  discoveredAccountSchema,
  resourceRefSchema,
  rawItemSchema,
  rawPageSchema,
  webhookEnvelopeSchema,
  outboundActionKindSchema,
  outboundActionInputSchema,
  outboundResultSchema,
  type Result,
  type FailureClass,
  type AppCredentials,
  type PkcePair,
  type TokenSet,
  type AuthCtx,
  type Logger,
  type HttpRequest,
  type HttpResponse,
  type HttpClient,
  type ObservedUsage,
  type BudgetReservation,
  type ReserveRequest,
  type SettleOutcome,
  type BudgetHandle,
  type ConnCtx,
  type NormalizeCtx,
  type DiscoveredAccount,
  type ScopeVerification,
  type ResourceRef,
  type RawItem,
  type RawPage,
  type WebhookRequest,
  type WebhookEnvelope,
  type OutboundActionKind,
  type OutboundActionInput,
  type OutboundAction,
  type OutboundResult,
  type Preflight,
  type HealthStatus,
  type HealthCheck,
  type HealthReport,
  type Connector,
} from './spi.ts';
