-- Phase 10: the workflow engine's persistent state (ADR-021) and the AI layer's cost ledger
-- (spec §13, §14). WorkflowVersion makes "versioning with rollback" a copy of an old row, not an
-- opaque diff; Workflow.state is the per-action scratch pad (e.g. round-robin cursor);
-- WorkflowRun.triggerKey makes a redelivered event idempotent; AiUsage is the per-workspace
-- token budget ledger; Identity.bioEmbedding is the Tier-3 signal ADR-017 deferred to Phase 10,
-- wired into the nightly re-score only.

-- AlterTable
ALTER TABLE "Identity" ADD COLUMN "bioEmbedding" vector(1536);

ALTER TABLE "Workflow" ADD COLUMN "state" JSONB NOT NULL DEFAULT '{}';

ALTER TABLE "WorkflowRun" ADD COLUMN "triggerKey" TEXT;

-- CreateTable
CREATE TABLE "WorkflowVersion" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "workflowId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "trigger" JSONB NOT NULL,
    "conditions" JSONB NOT NULL,
    "actions" JSONB NOT NULL,
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WorkflowVersion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AiUsage" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "feature" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "promptTokens" INTEGER NOT NULL,
    "completionTokens" INTEGER NOT NULL,
    "costCents" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AiUsage_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "WorkflowVersion_workflowId_version_key" ON "WorkflowVersion"("workflowId", "version");
CREATE INDEX "WorkflowVersion_workspaceId_workflowId_version_idx" ON "WorkflowVersion"("workspaceId", "workflowId", "version" DESC);

CREATE UNIQUE INDEX "WorkflowRun_workflowId_triggerKey_key" ON "WorkflowRun"("workflowId", "triggerKey");

CREATE INDEX "AiUsage_workspaceId_createdAt_idx" ON "AiUsage"("workspaceId", "createdAt" DESC);
CREATE INDEX "AiUsage_workspaceId_feature_createdAt_idx" ON "AiUsage"("workspaceId", "feature", "createdAt" DESC);

-- AddForeignKey
ALTER TABLE "WorkflowVersion" ADD CONSTRAINT "WorkflowVersion_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WorkflowVersion" ADD CONSTRAINT "WorkflowVersion_workflowId_fkey" FOREIGN KEY ("workflowId") REFERENCES "Workflow"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WorkflowVersion" ADD CONSTRAINT "WorkflowVersion_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "AiUsage" ADD CONSTRAINT "AiUsage_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- nexus:managed-outside-schema
-- Row-level security for the two new tenant tables (generated by scripts/gen-rls-sql.ts
-- --tables WorkflowVersion,AiUsage — same policy shape as every other tenant table).
ALTER TABLE "AiUsage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiUsage" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_AiUsage_tenant ON "AiUsage";
CREATE POLICY rls_AiUsage_tenant ON "AiUsage"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "WorkflowVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkflowVersion" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_WorkflowVersion_tenant ON "WorkflowVersion";
CREATE POLICY rls_WorkflowVersion_tenant ON "WorkflowVersion"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

-- Application role privileges (only when the role exists in this cluster).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nexus_app') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON "AiUsage" TO nexus_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON "WorkflowVersion" TO nexus_app';
  END IF;
END $$;
