-- nexus:managed-outside-schema
-- Row-level security (spec §5.1). Generated by scripts/gen-rls-sql.ts — do not hand-edit;
-- regenerate into a new migration when tenant models are added.
--
-- The application connects as the non-superuser role "nexus_app" (created by infra, see
-- infra/postgres/init.sql and the CI workflow). Migrations run as the table owner. FORCE makes
-- the policies apply to the owner too, so even a misconfigured DATABASE_URL is contained.




ALTER TABLE "ImportJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImportJob" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ImportJob_tenant ON "ImportJob";
CREATE POLICY rls_ImportJob_tenant ON "ImportJob"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

-- Application role privileges (only when the role exists in this cluster).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nexus_app') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA public TO nexus_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO nexus_app';
    EXECUTE 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nexus_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nexus_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO nexus_app';
  END IF;
END $$;
