/**
 * `pnpm nexus new-connector <name>` (spec §7.5): scaffold a connector package — manifest,
 * OAuth handlers, one resource, a fixture folder, the contract test suite wired to a
 * scripted platform double, and a docs page. The result typechecks and its tests pass before
 * a single platform detail is filled in; the TODOs mark exactly what to change.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { PLATFORMS } from '@nexus/connector-sdk';

export type ScaffoldOptions = {
  name: string;
  platform?: string;
  displayName?: string;
  rootDir: string;
  force?: boolean;
};

const kebab = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
const pascal = (s: string) =>
  kebab(s)
    .split('-')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');

export function renderTemplates(opts: ScaffoldOptions): Record<string, string> {
  const name = kebab(opts.name);
  const Name = pascal(name);
  const camel = Name.charAt(0).toLowerCase() + Name.slice(1);
  const platform = (opts.platform ?? name).toUpperCase().replace(/[^A-Z0-9_]/g, '_');
  if (!(PLATFORMS as readonly string[]).includes(platform)) {
    throw new Error(
      `${platform} is not a Platform yet. The one core touch a new platform needs: add it to the Platform enum in packages/db/prisma/schema.prisma (with a migration) and to PLATFORMS in packages/connectors/sdk/src/platform.ts, then run this again — or pass --platform <existing> to scaffold against an existing value.`,
    );
  }
  const display = opts.displayName ?? Name;
  const prefix = name.replace(/-/g, '_').slice(0, 6);
  const kind = `${prefix}_item`;
  const resource = `${prefix}.items`;
  const tpl = (s: string) =>
    s
      .replaceAll('__NAME__', name)
      .replaceAll('__PASCAL__', Name)
      .replaceAll('__CAMEL__', camel)
      .replaceAll('__PLATFORM__', platform)
      .replaceAll('__DISPLAY__', display)
      .replaceAll('__KIND__', kind)
      .replaceAll('__RESOURCE__', resource);

  return {
    [`packages/connectors/${name}/package.json`]: tpl(PACKAGE_JSON),
    [`packages/connectors/${name}/tsconfig.json`]: TSCONFIG,
    [`packages/connectors/${name}/vitest.config.ts`]: VITEST,
    [`packages/connectors/${name}/src/index.ts`]: tpl(INDEX),
    [`packages/connectors/${name}/src/manifest.ts`]: tpl(MANIFEST),
    [`packages/connectors/${name}/src/connector.ts`]: tpl(CONNECTOR),
    [`packages/connectors/${name}/src/fixtures/${kind}.json`]: tpl(FIXTURE),
    [`packages/connectors/${name}/src/connector.test.ts`]: tpl(TEST),
    [`docs/connectors/${name}.md`]: tpl(DOC),
  };
}

export function scaffoldConnector(opts: ScaffoldOptions): string[] {
  const files = renderTemplates(opts);
  const written: string[] = [];
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(opts.rootDir, rel);
    if (existsSync(abs) && !opts.force)
      throw new Error(`${rel} already exists (pass --force to overwrite)`);
    mkdirSync(path.dirname(abs), { recursive: true });
    writeFileSync(abs, content);
    written.push(rel);
  }
  return written;
}

const PACKAGE_JSON = `{
  "name": "@nexus/connector-__NAME__",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "description": "__DISPLAY__ connector for Nexus (generated by pnpm nexus new-connector).",
  "exports": {
    ".": "./src/index.ts"
  },
  "scripts": {
    "typecheck": "tsc --noEmit -p tsconfig.json",
    "test": "vitest run",
    "lint": "eslint ."
  },
  "dependencies": {
    "@nexus/connector-sdk": "workspace:*",
    "@nexus/core": "workspace:*",
    "zod": "^4.6.5"
  },
  "devDependencies": {
    "typescript": "5.9.3",
    "vitest": "^5.0.1"
  }
}
`;

const TSCONFIG = `{
  "extends": "../../../tsconfig.base.json",
  "compilerOptions": {
    "rootDir": "."
  },
  "include": ["src", "*.config.ts"]
}
`;

const VITEST = `import { defineConfig } from 'vitest/config';
export default defineConfig({ test: { include: ['src/**/*.test.ts'] } });
`;

const INDEX = `export { create__PASCAL__Connector } from './connector.ts';
export type { __PASCAL__Config } from './connector.ts';
export { __CAMEL__Manifest as manifest, KINDS } from './manifest.ts';
`;

const MANIFEST = `import { connectorManifestSchema, type ConnectorManifest } from '@nexus/connector-sdk';

export const KINDS = { item: '__KIND__' } as const;

/**
 * TODO(platform): pin the real API version, list every scope with its plain-language meaning,
 * describe each resource, pick the quota shape from §7.3 and write the constraints a user
 * must know. Everything the UI, the scheduler and the quota simulator show comes from here.
 */
export const __CAMEL__Manifest: ConnectorManifest = connectorManifestSchema.parse({
  platform: '__PLATFORM__',
  displayName: '__DISPLAY__',
  apiVersion: 'v1',
  docsUrl: 'https://developer.example.com/__NAME__',
  authKind: 'oauth2',
  scopes: [{ id: 'read', plainLanguage: 'Read your items', requiredFor: ['read:posts'], sensitive: false }],
  resources: [
    {
      id: '__RESOURCE__',
      displayName: 'Items',
      kinds: [KINDS.item],
      defaultIntervalSeconds: 300,
      defaultEnabled: true,
      supportsBackfill: true,
      supportsWebhook: false,
      costPerPage: 1,
      laneHints: { defaultLane: 'delta', allowedLanes: ['delta', 'backfill'] },
    },
  ],
  capabilities: ['read:posts'],
  quota: { kind: 'fixed_window', windowSeconds: 900, limit: 300 },
  webhooks: { supported: false, verification: 'none', resources: [], replayable: false },
  constraints: ['TODO(platform): document the gotchas users must know.'],
  tierNotes: 'TODO(platform): what the customer\\'s API plan must be.',
} satisfies ConnectorManifest);
`;

const CONNECTOR = `import { z } from 'zod';
import { NexusError } from '@nexus/core';
import {
  buildAuthorizationUrl,
  exchangeAuthorizationCode,
  observedFromHeaders,
  refreshAccessToken,
  revokeToken,
  type BudgetHandle,
  type CanonicalEntity,
  type ConnCtx,
  type Connector,
  type HealthReport,
  type Preflight,
  type RawPage,
  type ResourceRef,
  type WebhookEnvelope,
  type WebhookRequest,
} from '@nexus/connector-sdk';
import { __CAMEL__Manifest, KINDS } from './manifest.ts';

export type __PASCAL__Config = {
  /** API origin — overridable so tests point at a double. */
  baseUrl: string;
};

// TODO(platform): the exact raw shape. Keep it strict: anything else is SCHEMA_DRIFT and gets quarantined.
const rawItemSchema = z.object({ id: z.string(), text: z.string(), createdAt: z.iso.datetime(), authorId: z.string() }).strict();
const listSchema = z.object({ data: z.array(z.unknown()), next: z.string().nullable() });

async function withBudget<T>(budget: BudgetHandle, endpoint: string, call: () => Promise<{ value: T; headers: Readonly<Record<string, string>>; status: number }>): Promise<T> {
  const r = await budget.reserve({ endpoint, cost: 1 });
  if (!r.ok) throw r.error;
  try {
    const res = await call();
    await budget.settle(r.value, { observed: observedFromHeaders(res.headers, Date.now()), httpStatus: res.status });
    return res.value;
  } catch (e) {
    await budget.settle(r.value, { httpStatus: e instanceof NexusError && typeof e.details.status === 'number' ? e.details.status : undefined });
    throw e;
  }
}

export function create__PASCAL__Connector(config: __PASCAL__Config): Connector<__PASCAL__Config> {
  const base = config.baseUrl.replace(/\\/+$/, '');
  const bearer = async (ctx: ConnCtx<__PASCAL__Config>) => ({ authorization: \`Bearer \${(await ctx.token()).accessToken}\` });

  const connector: Connector<__PASCAL__Config> = {
    manifest: __CAMEL__Manifest,

    buildAuthUrl(ctx, opts) {
      // TODO(platform): authorize URL, client id source, extra params.
      return buildAuthorizationUrl({ authorizeUrl: \`\${base}/oauth/authorize\`, clientId: 'TODO-client-id', redirectUri: ctx.redirectUri, scopes: opts.scopes, state: opts.state, pkce: opts.pkce });
    },
    async exchangeCode(ctx, code, verifier) {
      const creds = await ctx.appCredentials();
      return exchangeAuthorizationCode(ctx.http, { tokenUrl: \`\${base}/oauth/token\`, clientId: creds.clientId, clientSecret: creds.clientSecret, code, redirectUri: ctx.redirectUri, verifier });
    },
    async refresh(ctx, token) {
      const creds = await ctx.appCredentials();
      return refreshAccessToken(ctx.http, { tokenUrl: \`\${base}/oauth/token\`, clientId: creds.clientId, clientSecret: creds.clientSecret, token });
    },
    async revoke(ctx, token) {
      const creds = await ctx.appCredentials();
      await revokeToken(ctx.http, { revokeUrl: \`\${base}/oauth/revoke\`, clientId: creds.clientId, clientSecret: creds.clientSecret, token: token.accessToken });
    },
    async discoverAccounts(ctx) {
      // TODO(platform): list the sub-accounts the user may attach.
      return [{ externalId: ctx.accountExternalId, platform: '__PLATFORM__', name: 'Account', handle: null, avatarUrl: null, accountType: 'account', hasOwnToken: false, parentExternalId: null, raw: {} }];
    },
    async verifyScopes(ctx) {
      const granted = new Set((await ctx.token()).scopes);
      const missing = __CAMEL__Manifest.scopes.filter((s) => !granted.has(s.id)).map((s) => s.id);
      const degraded = [...new Set(__CAMEL__Manifest.scopes.filter((s) => missing.includes(s.id)).flatMap((s) => s.requiredFor))];
      return { missing, degraded };
    },

    listResources() {
      return __CAMEL__Manifest.resources;
    },
    async fetchPage(ctx, r: ResourceRef, cursor?: string): Promise<RawPage> {
      if (r.id !== '__RESOURCE__') throw new NexusError('VALIDATION', { message: \`unknown resource \${r.id}\` });
      const endpoint = 'GET /v1/items';
      const body = await withBudget(ctx.budget, endpoint, async () => {
        const res = await ctx.http.request({ method: 'GET', url: \`\${base}/v1/items\`, query: { cursor, limit: r.pageSize ?? 100, since: (r.highWaterMark ?? r.since)?.toISOString() }, headers: await bearer(ctx), endpoint, signal: ctx.signal });
        return { value: listSchema.parse(res.json()), headers: res.headers, status: res.status };
      });
      let hwm: Date | undefined;
      const items = body.data.map((raw) => {
        const o = raw as { id?: unknown; createdAt?: unknown };
        const at = typeof o.createdAt === 'string' ? new Date(o.createdAt) : undefined;
        if (at && !Number.isNaN(at.getTime()) && (!hwm || at > hwm)) hwm = at;
        return { kind: KINDS.item, externalId: typeof o.id === 'string' ? o.id : '', raw, occurredAt: at };
      });
      return { items, nextCursor: body.next, budgetSpent: 1, highWaterMark: hwm };
    },
    verifyWebhook(_req: WebhookRequest, _secret: string): boolean {
      return false; // TODO(platform): verifyHmacSha256 / verifySharedSecret / verifyJwtRs256 from the SDK.
    },
    parseWebhook(_req: WebhookRequest): WebhookEnvelope[] {
      return [];
    },
    async subscribeWebhooks() {
      // TODO(platform): idempotent subscription, or leave empty when the platform has no push.
    },

    normalize(kind, raw, ctx): CanonicalEntity[] {
      if (kind !== KINDS.item) throw new NexusError('SCHEMA_DRIFT', { message: \`unknown kind \${kind}\` });
      const item = rawItemSchema.parse(raw);
      // TODO(platform): map to the right canonical entities (§7.2).
      return [
        {
          kind: 'post',
          platform: '__PLATFORM__',
          externalId: item.id,
          occurredAt: new Date(item.createdAt),
          sourceUrl: null,
          raw,
          parentExternalId: null,
          rootExternalId: null,
          authorExternalId: item.authorId || ctx.accountExternalId,
          postType: 'original',
          mediaType: 'text',
          body: item.text,
          media: [],
          publishedAt: new Date(item.createdAt),
        },
      ];
    },

    async capabilities(ctx) {
      const v = await connector.verifyScopes(ctx);
      return __CAMEL__Manifest.capabilities.filter((c) => !v.degraded.includes(c));
    },
    async preflight(): Promise<Preflight> {
      return { ok: false, code: 'POLICY_BLOCKED', reason: '__DISPLAY__ is read-only in this connector', remediation: 'No outbound actions are available yet.' };
    },
    async execute() {
      throw new NexusError('POLICY_BLOCKED', { message: 'read-only connector' });
    },

    async budget(ctx) {
      return ctx.budget.snapshot();
    },
    async health(ctx): Promise<HealthReport> {
      const checks: HealthReport['checks'] = [];
      let status: HealthReport['status'] = 'healthy';
      try {
        await ctx.http.request({ method: 'GET', url: \`\${base}/v1/health\`, endpoint: 'GET /v1/health', signal: ctx.signal, timeoutMs: 5_000 });
        checks.push({ id: 'reachability', ok: true });
      } catch (e) {
        checks.push({ id: 'reachability', ok: false, failureClass: e instanceof NexusError ? e.code : 'PLATFORM_DOWN', detail: e instanceof Error ? e.message : String(e) });
        status = 'down';
      }
      return { status, checks, tokenExpiresAt: null, degradedCapabilities: [], lastError: null, checkedAt: new Date() };
    },
  };
  return connector;
}
`;

const FIXTURE = `{
  "id": "item_1",
  "text": "hello from __DISPLAY__",
  "createdAt": "2026-09-01T12:00:00.000Z",
  "authorId": "user_1"
}
`;

const TEST = `import { describe, expect, it } from 'vitest';
import { defineConnectorContract } from '@nexus/connector-sdk/contract';
import { createTestConnCtx, createTestNormalizeCtx, jsonResponse } from '@nexus/connector-sdk/testing';
import { create__PASCAL__Connector } from './connector.ts';
import { __CAMEL__Manifest, KINDS } from './manifest.ts';
import fixture from './fixtures/__KIND__.json' with { type: 'json' };

const config = { baseUrl: 'https://__NAME__.example.test' };
const connector = create__PASCAL__Connector(config);

/** A three-page platform double. Replace with recorded fixtures as you learn the real shapes. */
function platformDouble(mode: 'ok' | '429' | '401' = 'ok') {
  const pages = [0, 1, 2].map((p) => ({
    data: Array.from({ length: 3 }, (_, i) => ({ ...fixture, id: \`item_\${p * 3 + i}\`, createdAt: new Date(Date.UTC(2026, 8, 1 + p, i)).toISOString() })),
    next: p < 2 ? String(p + 1) : null,
  }));
  return async (url: string): Promise<Response> => {
    if (mode === '429') return jsonResponse(429, { error: 'rate_limited' }, { 'retry-after': '1' });
    if (mode === '401') return jsonResponse(401, { error: 'invalid_token' });
    const u = new URL(url);
    if (u.pathname.endsWith('/v1/health')) return jsonResponse(200, { ok: true });
    const page = pages[Number(u.searchParams.get('cursor') ?? '0')] ?? pages[0]!;
    return jsonResponse(200, page, { 'x-rate-limit-limit': '300', 'x-rate-limit-remaining': '299' });
  };
}

const ctx = (mode: 'ok' | '429' | '401' = 'ok') => createTestConnCtx({ manifest: __CAMEL__Manifest, fetch: platformDouble(mode), config, retry: { maxAttempts: 1 } });

defineConnectorContract(
  { describe, it, expect },
  {
    connector,
    makeCtx: () => ctx(),
    scenarios: { rateLimited: () => ctx('429'), expiredToken: () => ctx('401') },
    fixtures: [{ kind: KINDS.item, raw: fixture }],
    normalizeCtx: createTestNormalizeCtx(__CAMEL__Manifest),
  },
);

describe('__DISPLAY__ normalize', () => {
  it('matches the golden output', () => {
    expect(connector.normalize(KINDS.item, fixture, createTestNormalizeCtx(__CAMEL__Manifest))).toMatchSnapshot();
  });
});
`;

const DOC = `# __DISPLAY__ connector

> Generated by \`pnpm nexus new-connector __NAME__\`. Fill in every section before the connector
> leaves the read-only stage (spec §8: endpoints, scopes, webhook topics, quota math, messaging
> windows, failure codes → remediation, fixture inventory).

## Endpoints used

| Purpose | Endpoint | Cost |
|---|---|---|
| List items | \`GET /v1/items\` | 1 call |

## Scopes

| Scope | Plain language | Required for |
|---|---|---|
| \`read\` | Read your items | \`read:posts\` |

## Quota

Fixed window: 300 calls / 15 minutes (TODO: verify against the platform's live docs).

## Webhooks

None yet. Every resource is reconciled by polling.

## Failure codes → remediation

| Platform code | Class | What the user sees |
|---|---|---|
| 401 | AUTH_EXPIRED | Reconnect __DISPLAY__ |

## Fixtures

- \`src/fixtures/__KIND__.json\` — one recorded item (secrets scrubbed).
`;
