-- Phase 11: the Reports screen (§12.2.E) — dashboards and the fixed widget catalogue (§12.4).
-- No model for this existed before Phase 11; the earlier phases' schema never anticipated it.

-- CreateEnum
CREATE TYPE "WidgetKind" AS ENUM ('STAT_TILE', 'LINE', 'BAR', 'STACKED_BAR', 'FUNNEL', 'COHORT_HEATMAP', 'TABLE');

-- CreateTable
CREATE TABLE "Dashboard" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "ownerId" TEXT,
    "isShared" BOOLEAN NOT NULL DEFAULT false,
    "position" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "Dashboard_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DashboardWidget" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "dashboardId" TEXT NOT NULL,
    "kind" "WidgetKind" NOT NULL,
    "title" TEXT NOT NULL,
    "query" JSONB NOT NULL DEFAULT '{}',
    "position" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "DashboardWidget_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Dashboard_workspaceId_position_idx" ON "Dashboard"("workspaceId", "position");
CREATE INDEX "Dashboard_workspaceId_ownerId_idx" ON "Dashboard"("workspaceId", "ownerId");
CREATE INDEX "Dashboard_ownerId_idx" ON "Dashboard"("ownerId");

CREATE INDEX "DashboardWidget_workspaceId_dashboardId_position_idx" ON "DashboardWidget"("workspaceId", "dashboardId", "position");
CREATE INDEX "DashboardWidget_dashboardId_idx" ON "DashboardWidget"("dashboardId");

-- AddForeignKey
ALTER TABLE "Dashboard" ADD CONSTRAINT "Dashboard_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Dashboard" ADD CONSTRAINT "Dashboard_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "DashboardWidget" ADD CONSTRAINT "DashboardWidget_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DashboardWidget" ADD CONSTRAINT "DashboardWidget_dashboardId_fkey" FOREIGN KEY ("dashboardId") REFERENCES "Dashboard"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- nexus:managed-outside-schema
-- Row-level security for the two new tenant tables (generated by scripts/gen-rls-sql.ts
-- --tables Dashboard,DashboardWidget — same policy shape as every other tenant table).
ALTER TABLE "Dashboard" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Dashboard" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Dashboard_tenant ON "Dashboard";
CREATE POLICY rls_Dashboard_tenant ON "Dashboard"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

ALTER TABLE "DashboardWidget" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DashboardWidget" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_DashboardWidget_tenant ON "DashboardWidget";
CREATE POLICY rls_DashboardWidget_tenant ON "DashboardWidget"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());

-- Application role privileges (only when the role exists in this cluster).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nexus_app') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON "Dashboard" TO nexus_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON "DashboardWidget" TO nexus_app';
  END IF;
END $$;
