/**
 * Emits the row-level-security SQL for every tenant table (§5.1): enable + force RLS, one
 * policy per table comparing "workspaceId" with `app.workspace_id`, a bypass switch for system
 * jobs, and grants for the non-superuser application role.
 *
 * Usage: tsx scripts/gen-rls-sql.ts --out prisma/migrations/<ts>_rls_policies/migration.sql
 *
 * Idempotent (DROP POLICY IF EXISTS), so when a new tenant model is added, run it again into a
 * new migration folder. src/rls.test.ts fails if any tenant table lacks a policy in the
 * migrations directory, so a new model cannot be forgotten.
 */
import { writeFileSync } from 'node:fs';
import {
  modelMetaFromDataModel,
  readRuntimeDataModel,
  tenantModelsFromDataModel,
} from './tenant-models-from-dmmf.ts';

export const APP_ROLE = 'nexus_app';

export function renderRlsSql(tables: readonly string[], tablesOnly = false): string {
  const perTable = tables
    .map(
      (t) => `ALTER TABLE "${t}" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "${t}" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_${t}_tenant ON "${t}";
CREATE POLICY rls_${t}_tenant ON "${t}"
  USING ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("workspaceId" = nexus_current_workspace() OR nexus_rls_bypass());`,
    )
    .join('\n\n');

  return `-- nexus:managed-outside-schema
-- Row-level security (spec §5.1). Generated by scripts/gen-rls-sql.ts — do not hand-edit;
-- regenerate into a new migration when tenant models are added.
--
-- The application connects as the non-superuser role "${APP_ROLE}" (created by infra, see
-- infra/postgres/init.sql and the CI workflow). Migrations run as the table owner. FORCE makes
-- the policies apply to the owner too, so even a misconfigured DATABASE_URL is contained.

${
  tablesOnly
    ? ''
    : `DROP FUNCTION IF EXISTS nexus_current_workspace();
CREATE FUNCTION nexus_current_workspace() RETURNS text
  LANGUAGE sql STABLE PARALLEL SAFE
  AS $$ SELECT NULLIF(current_setting('app.workspace_id', true), '') $$;

CREATE OR REPLACE FUNCTION nexus_rls_bypass() RETURNS boolean
  LANGUAGE sql STABLE PARALLEL SAFE
  AS $ SELECT COALESCE(current_setting('app.rls_bypass', true), '') = 'on' $;
`
}

${
  tablesOnly
    ? ''
    : `-- The tenant root is reachable only as the current workspace (or with bypass).
ALTER TABLE "Workspace" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Workspace" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_Workspace_tenant ON "Workspace";
CREATE POLICY rls_Workspace_tenant ON "Workspace"
  USING ("id" = nexus_current_workspace() OR nexus_rls_bypass())
  WITH CHECK ("id" = nexus_current_workspace() OR nexus_rls_bypass());
`
}
${perTable}

-- Application role privileges (only when the role exists in this cluster).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_ROLE}') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA public TO ${APP_ROLE}';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${APP_ROLE}';
    EXECUTE 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${APP_ROLE}';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_ROLE}';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${APP_ROLE}';
  END IF;
END $$;
`;
}

export function tenantTables(): string[] {
  const dm = readRuntimeDataModel();
  const meta = modelMetaFromDataModel(dm);
  return tenantModelsFromDataModel(dm).map((m) => meta[m]?.table ?? m);
}

const outFlag = process.argv.indexOf('--out');
if (outFlag !== -1) {
  const out = process.argv[outFlag + 1];
  if (!out) {
    console.error('gen-rls-sql: --out <file> required');
    process.exit(2);
  }
  const onlyFlag = process.argv.indexOf('--tables');
  const only = onlyFlag !== -1 ? new Set((process.argv[onlyFlag + 1] ?? '').split(',')) : null;
  const tables = tenantTables().filter((t) => !only || only.has(t));
  writeFileSync(out, renderRlsSql(tables, only !== null), 'utf8');
  console.log(`gen-rls-sql: wrote ${out} (${tables.length} tenant tables + Workspace).`);
}
